spring:
  profiles:
    active: dev
    include:
      - base-addi
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      name: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangka512@gmail.com
    password: NEED_TO_EMPTY
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO
    com.ll.donggibook.app: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  order:
    cancelAvailableSeconds: 600
  rebate:
    wholesalePriceRate: 0.5
  site:
    name: DONGGI-BOOK
    baseUrl: "http://localhost:8010"
